# Generated by Django 4.2.5 on 2023-11-03 19:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='traco',
            name='nome',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
